In [27]:
IMAGE_HEIGHT = 10
IMAGE_WIDTH = 10

In [26]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import torch.nn.functional as F

model_name = "TheBloke/Mistral-7B-Instruct-v0.2-GPTQ"

# load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

In [28]:
encoded = tokenizer.encode("Hello world", return_tensors="pt")

In [29]:
encoded

tensor([[    1, 22557,  1526]])

In [55]:
total_image_size = IMAGE_HEIGHT * IMAGE_WIDTH
difference = total_image_size - len(encoded.squeeze())
if difference < 0: raise Exception("NOT IMPLEMENTED")

left_half = (difference) // 2
right_half = left_half
if left_half != (difference - left_half):
  print(f"difference: {difference-left_half}, half: {left_half}")
  right_half = difference - left_half

normalized_encoding = F.normalize(encoded.to(torch.float16))
padded = F.pad(normalized_encoding, [left_half, right_half])
padded.reshape((IMAGE_HEIGHT, IMAGE_WIDTH))

difference: 49, half: 48


tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 4.4227e-05, 9.9805e-01],
        [6.7505e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000

In [38]:
encoded.to(torch.float16)

tensor([[1.0000e+00, 2.2560e+04, 1.5260e+03]], dtype=torch.float16)