In [83]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import torch.nn.functional as F
from PIL import Image
import torchvision
import torchvision.transforms as transforms
import numpy as np

In [84]:
IMAGE_HEIGHT = 2160
IMAGE_WIDTH = 3840
COLORS = 3

In [85]:
model_name = "TheBloke/Mistral-7B-Instruct-v0.2-GPTQ"

# load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

In [86]:
encoded = tokenizer.encode("Hello world, how are you? Is this a lot?", return_tensors="pt")

In [87]:
encoded

tensor([[    1, 22557,  1526, 28725,   910,   460,   368, 28804,  1691,   456,
           264,  2055, 28804]])

In [88]:
total_image_size = IMAGE_HEIGHT * IMAGE_WIDTH * COLORS
difference = total_image_size - len(encoded.squeeze())
if difference < 0: raise Exception("NOT IMPLEMENTED")

left_half = (difference) // 2
right_half = left_half
if left_half != (difference - left_half):
  print(f"difference: {difference-left_half}, half: {left_half}")
  right_half = difference - left_half

normalized_encoding = encoded.to(torch.float64) / (255 * total_image_size)
padded = F.pad(normalized_encoding, [left_half, right_half])
reshaped_padded = padded.reshape((COLORS, IMAGE_HEIGHT, IMAGE_WIDTH))

difference: 12441594, half: 12441593


In [89]:
(normalized_encoding * (255 * total_image_size)).to(torch.int32)

tensor([[    1, 22557,  1526, 28724,   910,   459,   368, 28804,  1691,   456,
           264,  2055, 28804]], dtype=torch.int32)

In [90]:
tokenizer.decode((normalized_encoding * (255 * total_image_size)).to(torch.int32).squeeze().tolist())

'<s> Hello worldy how not you? Is this a lot?'

# Image Concatenation

In [91]:
transform = transforms.Compose([transforms.PILToTensor()])

image = transform(Image.open("BackgroundPicture1.jpg"))

In [92]:
image.shape

torch.Size([3, 2160, 3840])

In [93]:
(image + reshaped_padded).numpy().astype(np.uint8).shape

(3, 2160, 3840)

In [94]:
# result = Image.fromarray((image + reshaped_padded).numpy().astype(np.uint8).reshape(IMAGE_WIDTH, IMAGE_HEIGHT, COLORS))
reshaped_padded[reshaped_padded != 0] = 200
result = transforms.ToPILImage()((image + reshaped_padded.to(torch.uint8)))
result.save("resultTest.jpg")

In [101]:
reshaped_padded[reshaped_padded != 0].to(torch.uint8)

tensor([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
       dtype=torch.uint8)

In [99]:
test = (image -  transforms.PILToTensor()(result))
test[test != 0]

tensor([56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56], dtype=torch.uint8)